### ISSUE TITLE
Only Engine Code

### ISSUE THREAD

**Issue by Rashmatash** [ajweeks/FlexEngine#2]
Thank you for sharing this. It would be great if it was possible to only get your code  (excluding all the binaries and dependencies). That would be maybe a couple of MB's. Now I have to wait for a GB's worth of data to download. Maybe there's a Git option for this that I'm unaware of.

**Comment by ajweeks** [comment]
Most of the dependencies are submodules, meaning a regular `git clone` won't pull them. I agree that it's unfortunate that the resource files and binaries are included in the repo as they greatly bloat the size. I'm considering hosting the resource files elsewhere to address this issue, but for now I think the repository's size is still reasonable.
