### ISSUE TITLE
linux portability

### ISSUE THREAD

**Issue by renexdev** [ajweeks/FlexEngine#3]
Hi @ajweeks  I'm quite new in game/graphics programming and I started reading your blog with the interest put on how a rendering engine works. I'm using linux based system, the question if is there is possible to export a  CMakeLists.txt config file from your project in order to give it a try with cmake.  Thanks in advance

**Comment by ajweeks** [comment]
Hi, I've been wanting to add linux support for quite a while - it just hasn't been a priority. You should be able to use GENie to generate project files on linux. You can down it [here](https://github.com/bkaradzic/GENie) and then call it in a similar way to `scripts/generate-vs-2017-files.bat`. 

The project has not been compiled on linux however, and I imagine there will be considerable work involved with getting it working. I can update you once that is done, but I'm not sure it will be happening any time soon. I am open to someone making the necessary changes and making a pull request though!

I haven't used it/looked into it myself, but [bgfx](https://github.com/bkaradzic/bgfx) looks like a decent (but maybe slightly daunting) resource for learning about modern rendering engines.

**Comment by renexdev** [comment]
Ok, thanks for the quick response and the suggestion on bgfx.

**Comment by ajweeks** [comment]
Hi @renexdev, for what it's worth Flex engine now compiles on linux (well, at least on Ubuntu 18.04). Build instructions are described in build.md if you're interested.
